// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VALU.h for the primary calling header

#ifndef VERILATED_VALU_CARRY_LOOKAHEAD_ADDER_H_
#define VERILATED_VALU_CARRY_LOOKAHEAD_ADDER_H_  // guard

#include "verilated.h"


class VALU__Syms;

class alignas(VL_CACHE_LINE_BYTES) VALU_carry_lookahead_adder final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(Subtract,0,0);
        VL_IN8(cin,0,0);
        VL_OUT8(cout,0,0);
        CData/*6:0*/ c;
        CData/*0:0*/ cin_effective;
        CData/*3:0*/ block0__DOT__a;
        CData/*3:0*/ block0__DOT__b;
        CData/*0:0*/ block0__DOT__cin;
        CData/*3:0*/ block0__DOT__s;
        CData/*0:0*/ block0__DOT__cout;
        CData/*3:0*/ block0__DOT__P;
        CData/*3:0*/ block0__DOT__G;
        CData/*0:0*/ block0__DOT__c0;
        CData/*0:0*/ block0__DOT__c1;
        CData/*0:0*/ block0__DOT__c2;
        CData/*0:0*/ block0__DOT____Vcellout__slice0__P;
        CData/*0:0*/ block0__DOT____Vcellout__slice0__G;
        CData/*0:0*/ block0__DOT____Vcellout__slice1__P;
        CData/*0:0*/ block0__DOT____Vcellout__slice1__G;
        CData/*0:0*/ block0__DOT____Vcellout__slice2__P;
        CData/*0:0*/ block0__DOT____Vcellout__slice2__G;
        CData/*0:0*/ block0__DOT____Vcellout__slice3__P;
        CData/*0:0*/ block0__DOT____Vcellout__slice3__G;
        CData/*0:0*/ block0__DOT__slice0__DOT__a;
        CData/*0:0*/ block0__DOT__slice0__DOT__b;
        CData/*0:0*/ block0__DOT__slice0__DOT__G;
        CData/*0:0*/ block0__DOT__slice0__DOT__P;
        CData/*0:0*/ block0__DOT__slice1__DOT__a;
        CData/*0:0*/ block0__DOT__slice1__DOT__b;
        CData/*0:0*/ block0__DOT__slice1__DOT__G;
        CData/*0:0*/ block0__DOT__slice1__DOT__P;
        CData/*0:0*/ block0__DOT__slice2__DOT__a;
        CData/*0:0*/ block0__DOT__slice2__DOT__b;
        CData/*0:0*/ block0__DOT__slice2__DOT__G;
        CData/*0:0*/ block0__DOT__slice2__DOT__P;
        CData/*0:0*/ block0__DOT__slice3__DOT__a;
        CData/*0:0*/ block0__DOT__slice3__DOT__b;
        CData/*0:0*/ block0__DOT__slice3__DOT__G;
        CData/*0:0*/ block0__DOT__slice3__DOT__P;
        CData/*3:0*/ block1__DOT__a;
        CData/*3:0*/ block1__DOT__b;
        CData/*0:0*/ block1__DOT__cin;
        CData/*3:0*/ block1__DOT__s;
        CData/*0:0*/ block1__DOT__cout;
        CData/*3:0*/ block1__DOT__P;
        CData/*3:0*/ block1__DOT__G;
        CData/*0:0*/ block1__DOT__c0;
        CData/*0:0*/ block1__DOT__c1;
        CData/*0:0*/ block1__DOT__c2;
        CData/*0:0*/ block1__DOT____Vcellout__slice0__P;
        CData/*0:0*/ block1__DOT____Vcellout__slice0__G;
        CData/*0:0*/ block1__DOT____Vcellout__slice1__P;
        CData/*0:0*/ block1__DOT____Vcellout__slice1__G;
        CData/*0:0*/ block1__DOT____Vcellout__slice2__P;
        CData/*0:0*/ block1__DOT____Vcellout__slice2__G;
        CData/*0:0*/ block1__DOT____Vcellout__slice3__P;
        CData/*0:0*/ block1__DOT____Vcellout__slice3__G;
        CData/*0:0*/ block1__DOT__slice0__DOT__a;
        CData/*0:0*/ block1__DOT__slice0__DOT__b;
        CData/*0:0*/ block1__DOT__slice0__DOT__G;
        CData/*0:0*/ block1__DOT__slice0__DOT__P;
        CData/*0:0*/ block1__DOT__slice1__DOT__a;
        CData/*0:0*/ block1__DOT__slice1__DOT__b;
        CData/*0:0*/ block1__DOT__slice1__DOT__G;
    };
    struct {
        CData/*0:0*/ block1__DOT__slice1__DOT__P;
        CData/*0:0*/ block1__DOT__slice2__DOT__a;
        CData/*0:0*/ block1__DOT__slice2__DOT__b;
        CData/*0:0*/ block1__DOT__slice2__DOT__G;
        CData/*0:0*/ block1__DOT__slice2__DOT__P;
        CData/*0:0*/ block1__DOT__slice3__DOT__a;
        CData/*0:0*/ block1__DOT__slice3__DOT__b;
        CData/*0:0*/ block1__DOT__slice3__DOT__G;
        CData/*0:0*/ block1__DOT__slice3__DOT__P;
        CData/*3:0*/ block2__DOT__a;
        CData/*3:0*/ block2__DOT__b;
        CData/*0:0*/ block2__DOT__cin;
        CData/*3:0*/ block2__DOT__s;
        CData/*0:0*/ block2__DOT__cout;
        CData/*3:0*/ block2__DOT__P;
        CData/*3:0*/ block2__DOT__G;
        CData/*0:0*/ block2__DOT__c0;
        CData/*0:0*/ block2__DOT__c1;
        CData/*0:0*/ block2__DOT__c2;
        CData/*0:0*/ block2__DOT____Vcellout__slice0__P;
        CData/*0:0*/ block2__DOT____Vcellout__slice0__G;
        CData/*0:0*/ block2__DOT____Vcellout__slice1__P;
        CData/*0:0*/ block2__DOT____Vcellout__slice1__G;
        CData/*0:0*/ block2__DOT____Vcellout__slice2__P;
        CData/*0:0*/ block2__DOT____Vcellout__slice2__G;
        CData/*0:0*/ block2__DOT____Vcellout__slice3__P;
        CData/*0:0*/ block2__DOT____Vcellout__slice3__G;
        CData/*0:0*/ block2__DOT__slice0__DOT__a;
        CData/*0:0*/ block2__DOT__slice0__DOT__b;
        CData/*0:0*/ block2__DOT__slice0__DOT__G;
        CData/*0:0*/ block2__DOT__slice0__DOT__P;
        CData/*0:0*/ block2__DOT__slice1__DOT__a;
        CData/*0:0*/ block2__DOT__slice1__DOT__b;
        CData/*0:0*/ block2__DOT__slice1__DOT__G;
        CData/*0:0*/ block2__DOT__slice1__DOT__P;
        CData/*0:0*/ block2__DOT__slice2__DOT__a;
        CData/*0:0*/ block2__DOT__slice2__DOT__b;
        CData/*0:0*/ block2__DOT__slice2__DOT__G;
        CData/*0:0*/ block2__DOT__slice2__DOT__P;
        CData/*0:0*/ block2__DOT__slice3__DOT__a;
        CData/*0:0*/ block2__DOT__slice3__DOT__b;
        CData/*0:0*/ block2__DOT__slice3__DOT__G;
        CData/*0:0*/ block2__DOT__slice3__DOT__P;
        CData/*3:0*/ block3__DOT__a;
        CData/*3:0*/ block3__DOT__b;
        CData/*0:0*/ block3__DOT__cin;
        CData/*3:0*/ block3__DOT__s;
        CData/*0:0*/ block3__DOT__cout;
        CData/*3:0*/ block3__DOT__P;
        CData/*3:0*/ block3__DOT__G;
        CData/*0:0*/ block3__DOT__c0;
        CData/*0:0*/ block3__DOT__c1;
        CData/*0:0*/ block3__DOT__c2;
        CData/*0:0*/ block3__DOT____Vcellout__slice0__P;
        CData/*0:0*/ block3__DOT____Vcellout__slice0__G;
        CData/*0:0*/ block3__DOT____Vcellout__slice1__P;
        CData/*0:0*/ block3__DOT____Vcellout__slice1__G;
        CData/*0:0*/ block3__DOT____Vcellout__slice2__P;
        CData/*0:0*/ block3__DOT____Vcellout__slice2__G;
        CData/*0:0*/ block3__DOT____Vcellout__slice3__P;
        CData/*0:0*/ block3__DOT____Vcellout__slice3__G;
        CData/*0:0*/ block3__DOT__slice0__DOT__a;
        CData/*0:0*/ block3__DOT__slice0__DOT__b;
        CData/*0:0*/ block3__DOT__slice0__DOT__G;
    };
    struct {
        CData/*0:0*/ block3__DOT__slice0__DOT__P;
        CData/*0:0*/ block3__DOT__slice1__DOT__a;
        CData/*0:0*/ block3__DOT__slice1__DOT__b;
        CData/*0:0*/ block3__DOT__slice1__DOT__G;
        CData/*0:0*/ block3__DOT__slice1__DOT__P;
        CData/*0:0*/ block3__DOT__slice2__DOT__a;
        CData/*0:0*/ block3__DOT__slice2__DOT__b;
        CData/*0:0*/ block3__DOT__slice2__DOT__G;
        CData/*0:0*/ block3__DOT__slice2__DOT__P;
        CData/*0:0*/ block3__DOT__slice3__DOT__a;
        CData/*0:0*/ block3__DOT__slice3__DOT__b;
        CData/*0:0*/ block3__DOT__slice3__DOT__G;
        CData/*0:0*/ block3__DOT__slice3__DOT__P;
        CData/*3:0*/ block4__DOT__a;
        CData/*3:0*/ block4__DOT__b;
        CData/*0:0*/ block4__DOT__cin;
        CData/*3:0*/ block4__DOT__s;
        CData/*0:0*/ block4__DOT__cout;
        CData/*3:0*/ block4__DOT__P;
        CData/*3:0*/ block4__DOT__G;
        CData/*0:0*/ block4__DOT__c0;
        CData/*0:0*/ block4__DOT__c1;
        CData/*0:0*/ block4__DOT__c2;
        CData/*0:0*/ block4__DOT____Vcellout__slice0__P;
        CData/*0:0*/ block4__DOT____Vcellout__slice0__G;
        CData/*0:0*/ block4__DOT____Vcellout__slice1__P;
        CData/*0:0*/ block4__DOT____Vcellout__slice1__G;
        CData/*0:0*/ block4__DOT____Vcellout__slice2__P;
        CData/*0:0*/ block4__DOT____Vcellout__slice2__G;
        CData/*0:0*/ block4__DOT____Vcellout__slice3__P;
        CData/*0:0*/ block4__DOT____Vcellout__slice3__G;
        CData/*0:0*/ block4__DOT__slice0__DOT__a;
        CData/*0:0*/ block4__DOT__slice0__DOT__b;
        CData/*0:0*/ block4__DOT__slice0__DOT__G;
        CData/*0:0*/ block4__DOT__slice0__DOT__P;
        CData/*0:0*/ block4__DOT__slice1__DOT__a;
        CData/*0:0*/ block4__DOT__slice1__DOT__b;
        CData/*0:0*/ block4__DOT__slice1__DOT__G;
        CData/*0:0*/ block4__DOT__slice1__DOT__P;
        CData/*0:0*/ block4__DOT__slice2__DOT__a;
        CData/*0:0*/ block4__DOT__slice2__DOT__b;
        CData/*0:0*/ block4__DOT__slice2__DOT__G;
        CData/*0:0*/ block4__DOT__slice2__DOT__P;
        CData/*0:0*/ block4__DOT__slice3__DOT__a;
        CData/*0:0*/ block4__DOT__slice3__DOT__b;
        CData/*0:0*/ block4__DOT__slice3__DOT__G;
        CData/*0:0*/ block4__DOT__slice3__DOT__P;
        CData/*3:0*/ block5__DOT__a;
        CData/*3:0*/ block5__DOT__b;
        CData/*0:0*/ block5__DOT__cin;
        CData/*3:0*/ block5__DOT__s;
        CData/*0:0*/ block5__DOT__cout;
        CData/*3:0*/ block5__DOT__P;
        CData/*3:0*/ block5__DOT__G;
        CData/*0:0*/ block5__DOT__c0;
        CData/*0:0*/ block5__DOT__c1;
        CData/*0:0*/ block5__DOT__c2;
        CData/*0:0*/ block5__DOT____Vcellout__slice0__P;
        CData/*0:0*/ block5__DOT____Vcellout__slice0__G;
        CData/*0:0*/ block5__DOT____Vcellout__slice1__P;
        CData/*0:0*/ block5__DOT____Vcellout__slice1__G;
        CData/*0:0*/ block5__DOT____Vcellout__slice2__P;
        CData/*0:0*/ block5__DOT____Vcellout__slice2__G;
        CData/*0:0*/ block5__DOT____Vcellout__slice3__P;
    };
    struct {
        CData/*0:0*/ block5__DOT____Vcellout__slice3__G;
        CData/*0:0*/ block5__DOT__slice0__DOT__a;
        CData/*0:0*/ block5__DOT__slice0__DOT__b;
        CData/*0:0*/ block5__DOT__slice0__DOT__G;
        CData/*0:0*/ block5__DOT__slice0__DOT__P;
        CData/*0:0*/ block5__DOT__slice1__DOT__a;
        CData/*0:0*/ block5__DOT__slice1__DOT__b;
        CData/*0:0*/ block5__DOT__slice1__DOT__G;
        CData/*0:0*/ block5__DOT__slice1__DOT__P;
        CData/*0:0*/ block5__DOT__slice2__DOT__a;
        CData/*0:0*/ block5__DOT__slice2__DOT__b;
        CData/*0:0*/ block5__DOT__slice2__DOT__G;
        CData/*0:0*/ block5__DOT__slice2__DOT__P;
        CData/*0:0*/ block5__DOT__slice3__DOT__a;
        CData/*0:0*/ block5__DOT__slice3__DOT__b;
        CData/*0:0*/ block5__DOT__slice3__DOT__G;
        CData/*0:0*/ block5__DOT__slice3__DOT__P;
        CData/*3:0*/ block6__DOT__a;
        CData/*3:0*/ block6__DOT__b;
        CData/*0:0*/ block6__DOT__cin;
        CData/*3:0*/ block6__DOT__s;
        CData/*0:0*/ block6__DOT__cout;
        CData/*3:0*/ block6__DOT__P;
        CData/*3:0*/ block6__DOT__G;
        CData/*0:0*/ block6__DOT__c0;
        CData/*0:0*/ block6__DOT__c1;
        CData/*0:0*/ block6__DOT__c2;
        CData/*0:0*/ block6__DOT____Vcellout__slice0__P;
        CData/*0:0*/ block6__DOT____Vcellout__slice0__G;
        CData/*0:0*/ block6__DOT____Vcellout__slice1__P;
        CData/*0:0*/ block6__DOT____Vcellout__slice1__G;
        CData/*0:0*/ block6__DOT____Vcellout__slice2__P;
        CData/*0:0*/ block6__DOT____Vcellout__slice2__G;
        CData/*0:0*/ block6__DOT____Vcellout__slice3__P;
        CData/*0:0*/ block6__DOT____Vcellout__slice3__G;
        CData/*0:0*/ block6__DOT__slice0__DOT__a;
        CData/*0:0*/ block6__DOT__slice0__DOT__b;
        CData/*0:0*/ block6__DOT__slice0__DOT__G;
        CData/*0:0*/ block6__DOT__slice0__DOT__P;
        CData/*0:0*/ block6__DOT__slice1__DOT__a;
        CData/*0:0*/ block6__DOT__slice1__DOT__b;
        CData/*0:0*/ block6__DOT__slice1__DOT__G;
        CData/*0:0*/ block6__DOT__slice1__DOT__P;
        CData/*0:0*/ block6__DOT__slice2__DOT__a;
        CData/*0:0*/ block6__DOT__slice2__DOT__b;
        CData/*0:0*/ block6__DOT__slice2__DOT__G;
        CData/*0:0*/ block6__DOT__slice2__DOT__P;
        CData/*0:0*/ block6__DOT__slice3__DOT__a;
        CData/*0:0*/ block6__DOT__slice3__DOT__b;
        CData/*0:0*/ block6__DOT__slice3__DOT__G;
        CData/*0:0*/ block6__DOT__slice3__DOT__P;
        CData/*3:0*/ block7__DOT__a;
        CData/*3:0*/ block7__DOT__b;
        CData/*0:0*/ block7__DOT__cin;
        CData/*3:0*/ block7__DOT__s;
        CData/*0:0*/ block7__DOT__cout;
        CData/*3:0*/ block7__DOT__P;
        CData/*3:0*/ block7__DOT__G;
        CData/*0:0*/ block7__DOT__c0;
        CData/*0:0*/ block7__DOT__c1;
        CData/*0:0*/ block7__DOT__c2;
        CData/*0:0*/ block7__DOT____Vcellout__slice0__P;
        CData/*0:0*/ block7__DOT____Vcellout__slice0__G;
        CData/*0:0*/ block7__DOT____Vcellout__slice1__P;
    };
    struct {
        CData/*0:0*/ block7__DOT____Vcellout__slice1__G;
        CData/*0:0*/ block7__DOT____Vcellout__slice2__P;
        CData/*0:0*/ block7__DOT____Vcellout__slice2__G;
        CData/*0:0*/ block7__DOT____Vcellout__slice3__P;
        CData/*0:0*/ block7__DOT____Vcellout__slice3__G;
        CData/*0:0*/ block7__DOT__slice0__DOT__a;
        CData/*0:0*/ block7__DOT__slice0__DOT__b;
        CData/*0:0*/ block7__DOT__slice0__DOT__G;
        CData/*0:0*/ block7__DOT__slice0__DOT__P;
        CData/*0:0*/ block7__DOT__slice1__DOT__a;
        CData/*0:0*/ block7__DOT__slice1__DOT__b;
        CData/*0:0*/ block7__DOT__slice1__DOT__G;
        CData/*0:0*/ block7__DOT__slice1__DOT__P;
        CData/*0:0*/ block7__DOT__slice2__DOT__a;
        CData/*0:0*/ block7__DOT__slice2__DOT__b;
        CData/*0:0*/ block7__DOT__slice2__DOT__G;
        CData/*0:0*/ block7__DOT__slice2__DOT__P;
        CData/*0:0*/ block7__DOT__slice3__DOT__a;
        CData/*0:0*/ block7__DOT__slice3__DOT__b;
        CData/*0:0*/ block7__DOT__slice3__DOT__G;
        CData/*0:0*/ block7__DOT__slice3__DOT__P;
        VL_IN(a,31,0);
        VL_IN(b,31,0);
        VL_OUT(s,31,0);
        IData/*31:0*/ b_in;
    };

    // INTERNAL VARIABLES
    VALU__Syms* const vlSymsp;

    // CONSTRUCTORS
    VALU_carry_lookahead_adder(VALU__Syms* symsp, const char* v__name);
    ~VALU_carry_lookahead_adder();
    VL_UNCOPYABLE(VALU_carry_lookahead_adder);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
