// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vshift_add.h for the primary calling header

#ifndef VERILATED_VSHIFT_ADD___024ROOT_H_
#define VERILATED_VSHIFT_ADD___024ROOT_H_  // guard

#include "verilated.h"


class Vshift_add__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vshift_add___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(start,0,0);
        VL_OUT8(count,6,0);
        VL_OUT8(done,0,0);
        VL_OUT8(running,0,0);
        CData/*0:0*/ shift_add__DOT__start;
        CData/*0:0*/ shift_add__DOT__clk;
        CData/*6:0*/ shift_add__DOT__count;
        CData/*0:0*/ shift_add__DOT__done;
        CData/*0:0*/ shift_add__DOT__running;
        CData/*1:0*/ shift_add__DOT__state;
        CData/*0:0*/ shift_add__DOT__cout_lower;
        CData/*0:0*/ shift_add__DOT__cout_upper;
        CData/*0:0*/ shift_add__DOT__start_pulse;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__Subtract;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__cin;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__cout;
        CData/*6:0*/ shift_add__DOT__adder_lower__DOT__c;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__cin_effective;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block0__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice2__DOT__a;
    };
    struct {
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block1__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block2__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block3__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__cout;
    };
    struct {
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block4__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block5__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice1__DOT__G;
    };
    struct {
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block6__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_lower__DOT__block7__DOT__slice3__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__Subtract;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__cin;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__cout;
        CData/*6:0*/ shift_add__DOT__adder_upper__DOT__c;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__cin_effective;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice3__DOT__b;
    };
    struct {
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block0__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block1__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block2__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__c2;
    };
    struct {
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block3__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block4__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice2__DOT__P;
    };
    struct {
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block5__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block6__DOT__slice3__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__a;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__cin;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__s;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__cout;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__P;
        CData/*3:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__c0;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__c1;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__c2;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice0__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice0__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice0__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice0__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice1__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice1__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice1__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice1__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice2__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice2__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice2__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice2__DOT__P;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice3__DOT__a;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice3__DOT__b;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice3__DOT__G;
        CData/*0:0*/ shift_add__DOT__adder_upper__DOT__block7__DOT__slice3__DOT__P;
        CData/*4:0*/ shift_add__DOT__rightshift_upper__DOT__shamt;
        CData/*4:0*/ shift_add__DOT__rightshift_lower__DOT__shamt;
        CData/*4:0*/ shift_add__DOT__rightshift_b__DOT__shamt;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __VactContinue;
        VL_IN(a,31,0);
    };
    struct {
        VL_IN(b,31,0);
        VL_OUT(b_in,31,0);
        VL_OUT(b_shifted,31,0);
        IData/*31:0*/ shift_add__DOT__a;
        IData/*31:0*/ shift_add__DOT__b;
        IData/*31:0*/ shift_add__DOT__b_in;
        IData/*31:0*/ shift_add__DOT__b_shifted;
        IData/*31:0*/ shift_add__DOT__adder_lower__DOT__a;
        IData/*31:0*/ shift_add__DOT__adder_lower__DOT__b;
        IData/*31:0*/ shift_add__DOT__adder_lower__DOT__s;
        IData/*31:0*/ shift_add__DOT__adder_lower__DOT__b_in;
        IData/*31:0*/ shift_add__DOT__adder_upper__DOT__a;
        IData/*31:0*/ shift_add__DOT__adder_upper__DOT__b;
        IData/*31:0*/ shift_add__DOT__adder_upper__DOT__s;
        IData/*31:0*/ shift_add__DOT__adder_upper__DOT__b_in;
        IData/*31:0*/ shift_add__DOT__rightshift_upper__DOT__a;
        IData/*31:0*/ shift_add__DOT__rightshift_upper__DOT__y;
        IData/*31:0*/ shift_add__DOT__rightshift_lower__DOT__a;
        IData/*31:0*/ shift_add__DOT__rightshift_lower__DOT__y;
        IData/*31:0*/ shift_add__DOT__rightshift_b__DOT__a;
        IData/*31:0*/ shift_add__DOT__rightshift_b__DOT__y;
        IData/*31:0*/ __VactIterCount;
        VL_OUT64(accumulator,63,0);
        VL_OUT64(padded_a,63,0);
        VL_OUT64(sum_holder,63,0);
        VL_OUT64(shifted_upper,63,0);
        VL_OUT64(shifted_lower,63,0);
        QData/*63:0*/ shift_add__DOT__accumulator;
        QData/*63:0*/ shift_add__DOT__padded_a;
        QData/*63:0*/ shift_add__DOT__sum_holder;
        QData/*63:0*/ shift_add__DOT__shifted_upper;
        QData/*63:0*/ shift_add__DOT__shifted_lower;
        QData/*63:0*/ shift_add__DOT__shifted_lower_corrected;
        VlUnpacked<IData/*31:0*/, 5> shift_add__DOT__rightshift_upper__DOT__stage;
        VlUnpacked<IData/*31:0*/, 5> shift_add__DOT__rightshift_lower__DOT__stage;
        VlUnpacked<IData/*31:0*/, 5> shift_add__DOT__rightshift_b__DOT__stage;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vshift_add__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vshift_add___024root(Vshift_add__Syms* symsp, const char* v__name);
    ~Vshift_add___024root();
    VL_UNCOPYABLE(Vshift_add___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
